development:
  adapter: postgresql
  database: db1
  host: did
  username: guest1
  password: guest1

test:
  adapter: mysql
  database: rails_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: rails_production
  host: localhost
  username: root
  password: 
